tarenpang/blockchain

block.js
block.test.js
package.json

added & tested static mineBlock() function

---

block.js
block.test.js
crypto-hash.js
crypto-hash.test.js

added mineBlock() and  cryptoHash()

---

blockchain.js
blockchain.test.js

tested & added Blockchain class

---

blockchain.js
blockchain.test.js

added chain validation

---

block.js
block.test.js
blockchain.js
config.js

added difficulty and nonce value

---

block.js
block.test.js
config.js

Please review and merge to main

added dynamic difficulty & the mine rate

---

block.js
block.test.js

added Difficulty in MineBlock

---

average-work.js
block.js
block.test.js
package-lock.json
package.json

refactored Proof of Work system to use Binary hashes

---

blockchain.js
blockchain.test.js

prevented Difficulty Jumps

---

index.js
package-lock.json
package.json

setup Express API

---

index.js
package-lock.json
package.json

setup endpoint to mine a block

---

index.js
package-lock.json
package.json
pubsub.js

implemented Broadcast Chain

---

index.js
package-lock.json
package.json

added Peers and Broadcast Chain on Mine endpoint

---

index.js
package-lock.json
package.json

implemented Sync Chain on Connect

---

index.js
pubsub.js

eliminated Redundant Interactions

---

config.js
wallet/index.js
wallet/index.test.js

created Wallet Class

---

package-lock.json
package.json
util/index.js
wallet/index.js
wallet/index.test.js

added ECC keyPair & Public Key Addresses

---

wallet/transaction.js
wallet/transaction.test.js

added Transaction Inputs

---

blockchain/block.js
blockchain/block.test.js
blockchain/index.js
blockchain/index.test.js
util/index.js
wallet/index.js
wallet/transaction.js
wallet/transaction.test.js

added Validate Transaction

---

wallet/index.js
wallet/index.test.js

added Wallet Create Transaction

---

util/crypto-hash.js
util/crypto-hash.test.js
wallet/transaction.js
wallet/transaction.test.js

updated TXs w Multiple Outputs & improved CryptoHash

---

wallet/transaction.js
wallet/transaction.test.js

updated Edge Cases

---

index.js

added transact endpoint & Main Tx Pool

---

index.js

handled Invalid Transactions w try...catch

---

index.js
wallet/transaction-pool.js
wallet/transaction-pool.test.js

added Transaction Updates in the API

---

index.js

added GET Transaction Pool Map endpoint

---

app/pubsub.js
index.js

added Broadcast Transaction

---

index.js
wallet/transaction-pool.js

synced Transaction Pool Map on Connect

---

app/transaction-miner.js

added Transaction Miner Class

---

wallet/transaction-pool.js
wallet/transaction-pool.test.js

added Valid Transactions function

---

config.js
wallet/transaction.js
wallet/transaction.test.js

implemented Miner Reward Transaction

---

wallet/transaction-pool.js
wallet/transaction-pool.test.js

added Clear Blockchain Transactions

---

app/transaction-miner.js
index.js

added Mine Transaction Endpoint

---

app/pubsub.js
blockchain/index.js

cleared TX pool upon successful replace

---

package-lock.json
package.json
wallet/index.js
wallet/index.test.js

added Calculate Wallet Balance

---

index.js
wallet/index.js
wallet/index.test.js

added Calc Balance before each TX

---

wallet/index.js
wallet/index.test.js

added Wallet Balance from Recent Transaction

---

index.js

added GET Wallet-Info endpoint

---

blockchain/index.js
blockchain/index.test.js

added Valid Transaction Data

---

blockchain/index.js
blockchain/index.test.js

validated Input Balances

---

blockchain/index.js
blockchain/index.test.js

prevented Duplicate Transactions in Block

---

app/pubsub.js
blockchain/index.js
blockchain/index.test.js

added Validate Transaction Chain

---

client/index.html
index.js

added Frontend Page

---

client/index.html
client/index.js
index.js
package-lock.json
package.json

added JS to the FE & installed parcel-bundler

---

client/index.js
client/src/index.html
client/src/index.js
index.js
package-lock.json
package.json

enabled React

---

client/src/index.js
package.json

enabled Frontend Development Workflow

---

client/src/components/App.js
client/src/index.js

added React App Component

---

client/src/components/App.js
package-lock.json
package.json

fetched Display Wallet-info

---

client/src/components/Block.js
client/src/components/Blocks.js

added the Block Component with Props

---

client/src/components/Block.js
package-lock.json
package.json

added Toggle Transaction Displays

---

client/src/components/Block.js
client/src/components/Transaction.js
client/src/index.css

added Transaction Component

---

client/src/components/ConductTransaction.js

added Post Transaction functionality

---

client/src/components/TransactionPool.js

added Mine Block through frontend functionality

---

app/pubsub.js
client/src/components/App.js
client/src/index.css
client/src/index.html
package-lock.json
package.json

switched from Redis to PubNub

---

app/pubsub.js
package-lock.json
package.json

installed DotEnv and put PubNub creds in .env file

---

app/pubsub.js
client/src/components/App.js
client/src/components/Blocks.js
client/src/components/ConductTransaction.js
index.js
package-lock.json
package.json

switched back to Redis; display most recent blocks first; added blocks pagination

---

client/src/components/Blocks.js

added backend and frontend folders in main directory

---

backend/block.js
backend/blockchain.js
backend/package-lock.json
backend/package.json

major backend overhaul - part 2

---

backend/blockchain.js
backend/index.js
backend/transaction.js

major backend overhaul - part 4

---

backend/index.js

major backend overhaul - part 5

---

backend/block.js
backend/blockchain.js
backend/index.js
backend/transaction.js
backend/utils/config.js
backend/utils/validationUtils.js

major backend overhaul - part 6

---

backend/blockchain.js
backend/index.js
backend/transaction.js

major backend overhaul - part 8

---

backend/block.js
backend/blockchain.js
backend/index.js
backend/utils/validationUtils.js

added /transaction/send through /peers endpoints

---

backend/blockchain.js
backend/index.js
backend/utils/config.js
backend/utils/cryptoUtils.js

enabled /peers/connect endpoint

---

backend/index.js
frontend/package-lock.json
frontend/package.json
frontend/src/navigation/SearchBar.jsx
frontend/src/pages/BlockDetails.jsx

updated backend/index.js /block/:blockHash endpoint

updated backend/index.js /block/:blockHash endpoint

---

frontend/package-lock.json
frontend/package.json
frontend/src/navigation/Navbar.jsx
frontend/src/pages/Faucet.jsx
frontend/src/pages/Wallet.jsx
frontend/vite.config.js

mui fix and wallet landing

---

backend/block.js
backend/blockchain.js
backend/transaction.js
backend/utils/config.js
frontend/custom.css
frontend/src/pages/AddressDetails.jsx
frontend/src/pages/BlockDetails.jsx
frontend/src/pages/Explorer.jsx
frontend/src/pages/Faucet.jsx
frontend/src/pages/Faucet_OLD.jsx
frontend/src/pages/Mine.jsx
frontend/src/pages/Wallet.jsx

updated frontend Faucet & Block Details pages

updated frontend Faucet & Block Details pages

---

frontend/custom.css
frontend/src/pages/BlockDetails.jsx
frontend/src/pages/Faucet.jsx
frontend/src/pages/Mine.jsx

added block properties to BlockDetail.jsx

added block properties to BlockDetail.jsx

---

frontend/custom.css
frontend/src/pages/BlockDetails.jsx
frontend/src/pages/Faucet.jsx

various minor adjustments

---

backend/index.js
backend/utils/config.js
frontend/custom.css
frontend/package.json
frontend/src/pages/Faucet.jsx
frontend/src/pages/Wallet.jsx
node_modules/.bin/conc
node_modules/.bin/concurrently
node_modules/.bin/tree-kill
node_modules/.package-lock.json
package-lock.json

faucet and donation

---

backend/index.js
frontend/src/pages/Faucet.jsx
frontend/src/pages/Mine.jsx

took out canTransact timer code in Faucet.jsx

took out canTransact timer code in Faucet.jsx

---

backend/blockchain.js
backend/index.js
frontend/src/pages/Faucet.jsx
frontend/src/pages/Mine.jsx

added hit /mine endpoint for all activeMinerPorts

added hit /mine endpoint for all activeMinerPorts
